import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import MenuBar from "@/app/ui/menubar";
import Header from "@/app/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="container-fluid">
          <div className="row"><Header/></div>
          <div className="row">
            <div className="col-2"><MenuBar/></div>
            <div className="col-10 p-3">{children}</div>
          </div>
        </div>
        </body>
    </html>
  );
}
